config/routes.rb
Rails.application.routes.draw do

  # root to: 'shelters#index'
  resources :shelters
  resources :animals do
    resources :adoption_processes
  end

  resources :users

  # get '/adoption_process/new', to: 'adoption_processes#new', as: '/adoption_form'
  # get '/animals/:id/adopt' to 
  # get '/snacks/:id', to: "snacks#show", as: "snack"

  get '/login', to: "sessions#login"
  post '/login', to: "sessions#process_login"
  get '/logout', to: "sessions#logout"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adoption_process.rb
class AdoptionProcess < ApplicationRecord
    belongs_to :user
    belongs_to :animal
end

app/models/animal.rb
class Animal < ApplicationRecord
    belongs_to :shelter
    has_many :adoption_processes
    has_many :users, through: :adoption_processes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shelter.rb
class Shelter < ApplicationRecord
    has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :adoption_processes
    has_many :animals, through: :adoption_processes

    validates :name, presence: true, uniqueness: true



end

app/controllers/adoption_processes_controller.rb
class AdoptionProcessesController < ApplicationController
    before_action :find_adoption_process, only: [:edit, :update, :destroy]
    
    def show

        @adoption_process = AdoptionProcess.where("animal_id = ? ", params[:animal_id])

        # @adoption_process = AdoptionProcess.new
        # @user = User.find(session[:user_id])
        # @animal = Animal.find(params[:id])
       
    end

    def new
        # byebug
        # @adoption_process = AdoptionProcess.where("animal_id = ? ", params[:animal_id])
        # byebug
        @adoption_process = AdoptionProcess.new
        @user = User.find(session[:user_id])
        @animal = Animal.find(params[:animal_id])
    end
    # user on animal#index
    # user clicks on animal#show
    # user clicks link to adopt animal
    # user taken to adoption_process#new
    # prefilled with user and pet info
    # after applying, user taken to adoption_process#show
    def create
        @adoption_process = AdoptionProcess.new(adoption_params)
        if @adoption_process.valid?
            @adoption_process.save
            redirect_to adoption_path(@adoption_process)
        else
            render :show
        end
    end

    def edit

    end

    def update
        @adoption_process.update(adoption_params)
        redirect_to adoption_path(@adoption_process)
        render :edit
    end

    def destroy

    end

    private
    def find_adoption_process
        @adoption_process = AdoptionProcess.find(params[:id])
    end
    def adoption_params
        params.require(:adoption_process).permit(:user_id, :animal_id, :status, :meeting_date)
    end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

    before_action :find_animal, only: [:show, :edit, :update]

    def index
        @animals = Animal.all
    end

    def show

    end

    def new
        
    end
    
    def create

    end

    def edit
        
    end

    def update

    end
    
    private

    def find_animal 
        @animal = Animal.find(params[:id])
    end

    def animal_params
        params.require(:animal).permit(:name, :age, :breed, :shelter_id, :bio)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        User.find(session[:user_id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login
        # loads login view
    end

    def process_login
        # processes form to login user

        # check if user with given username is in database 
        user = User.find_by(name: params[:name])
        if user && user.authenticate(params[:password])
        ## if they are, log them in and redirect to ?? index
            session[:user_id] = user.id
            redirect_to shelters_path
        else
            # if not, show an error and redisplay login form
            flash["error"] = "No user found with that name and password"
            render :login
        end
    end

    def logout
        session.delete(:user_id)
        redirect_to login_path
    end

end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

    def index

    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def index
        # @users = User.all
    end

    def show

    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def edit

    end

    def update

    end

    def destroy

    end

    private
    def find_user
        @user = User.find(params[:id])
    end
    def user_params
        params.require(:user).permit(:name, :password, :address, :age, :has_animals, :bio)
    end

end

app/helpers/adoption_processes_helper.rb
module AdoptionProcessesHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adoption_processes/index.html.erb
<h1>Adoption Form</h1>

app/views/adoption_processes/new.html.erb
<h1>Apply to Adopt this Furry Friend</h1>
<br>

<%= form_for @adoption_process, url: animal_adoption_processes_path(@animal, @adoption_process) do |f| %>

<%= f.label :animal_id %>
<%= f.text_field :animal_id, value: @animal.name %>
<%= f.label :user %>
<%= f.text_field :user, value: @user.name %>
<%= f.submit "Apply" %>
<% end %>

app/views/adoption_processes/show.html.erb
<h1>Apply to Adopt this Furry Friend</h1>
<br>
<%= form_for @adoption_process do |f|%>
<%= f.label :animal %>
<%= f.text_field :animal, value: @animal.name %>
<%= f.label :user %>
<%= f.text_field :user, value: @user.name %>
<%= f.submit "Apply" %>
<% end %>

app/views/animals/index.html.erb
<h1>All Our Amazing Friends</h1>

<h4><ul>
    <% @animals.each do |animal| %>
        <li>Name: <%= link_to animal.name, animal_path(animal) %> - Breed: <%= animal.breed %></li>
        <br><br>
    <% end %>
</ul></h4>

app/views/animals/show.html.erb
<h1>All About This Furry Friend</h1>
<br>
<h3>Name: <%= @animal.name %></h3>
<h3>Breed: <%= @animal.breed %></h3>
<h3>Age: <%= @animal.age %></h3>
<h3>Bio: <%= @animal.bio %></h3>
<!-- Add picture -->
<br>
<br>
<%= link_to 'View All Animals', animals_path %> 
<% if session[:user_id].nil? %>
   <div><%= link_to "Log In to Adopt", login_path %> </div> 
   <% end %>
<%= link_to 'Adopt This Animal', new_animal_adoption_process_path(@animal) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalShelter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
      <% if session[:user_id].nil? %>  
        <div><%= link_to "Login", login_path %></div>
      <% else %>
        <div>Welcome to our website, <%= current_user.name %></div>
        <div><%= link_to "Logout", logout_path %></div>
      <% end %>

    <%= yield %>
  </body>
</html>

app/views/shelters/index.html.erb
<h1>Welcome to Furrever</h1>

<%= link_to "All our animals", animals_path %>
<br>
<%= link_to "Apply to adopt", adoption_processes_path %>
<br>

app/views/users/new.html.erb
<h1>New User Sign Up</h1>
<br>
<%= form_for @user do |u| %>
<%= u.label :name %>
<%= u.text_field :name %>
<%= u.label :password %>
<%= u.password_field :password %>
<%= u.label :address %>
<%= u.text_field :address %>
<%= u.label :age %>
<%= u.number_field :age %>
<%= u.label :bio %>
<%= u.text_field :bio %>
<%= u.submit "Sign Up" %>
<% end %>
<br>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %>! </h1>
<br>
Name: <%= @user.name %>
<br>
Address: <%= @user.address %>
<br>
Age: <%= @user.age %>
<br>
Bio: <%= @user.bio %>